"##### general config #####
set fenc=utf-8

set expandtab
set shiftwidth=2
set tabstop=2
set autoindent


"SHOW
set number
set cursorline
set title
set showmatch
syntax on
set smartindent
colorscheme molokai
set background=dark

